description: Example async plugin
version: 0.0.1
remote: True
arguments:
endpoints:
  perform_operation:
    internal_name: perform_operation
    tags:
    remote: True
    accessible_by_other_plugins: True
    description:
    arguments:
      - name: arguments
        type: int
        description:

  perform_operation_stream_ABC:
    internal_name: perform_operation_stream
    tags:
    remote: True
    accessible_by_other_plugins: True
    description:
    arguments:
      - name: arguments
        type: int
        description:

  background_stream:
    internal_name: background_stream
    tags:
    remote: True
    accessible_by_other_plugins: True
    description:
    arguments:
      - name: arguments
        type: int
        description:
